apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-fastapi-kevin-inofuente
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/project-mlops-10-streamlit/repo-deploy-fastapi-cicd/image-v1-deploy-fastapi-cicd:latest
          env:
          ports:
            - containerPort: 8080